Script to compile only the tools you need
ANNIEsoft/ToolAnalysis pull request #325
Opened 2024-12-16 06:53 UTC by marvlad

## Describe your changes
I am adding a bash script in `script/` dir to compile in a `ToolAnalysis/build_[name_here]` directory only the needed tools. This speeds up the compilation time from 40 mins to ~3 minutes depending the tool. Additionally, the .gitignore was modify so the `build_*` dir doesn't interfere later.  

The script after `chmod +x ToolAnalysisMyTools.sh` in `scrip` can be run it  as `scrip/./ToolAnalysisMyTools.sh Tool` or `scrip./ToolAnalysisMyTools.sh "Tool1,Tool2,...` or `scrip./ToolAnalysisMyTools.sh Tool clean`. Allowing single Tool, or multiple tools.

## Checklist before submitting your PR
- [x] This PR implements a single change (one new/modified Tool, or a set of changes to implement one new/modified feature)
- [ ] This PR alters the minimum number of files to affect this change
- [ ] If this PR includes a new Tool, a README and minimal demonstration ToolChain is provided
- [ ] If a new Tool/ToolChain requires model or configuration files, their paths are not hard-coded, and means of generating those files is described in the readme, with examples provided on /pnfs/annie/persistent
- [ ] For every `new` usage, there is a reason the data must be on the heap
- [ ] For every `new` there is a `delete`, unless I explicitly know why (e.g. ROOT or a BoostStore takes ownership)

## Additional Material
Attach any validation or demonstration files here. You may also link to relavant docdb articles.

2024-12-16 16:13 UTC, marvlad commented
Adding a clarification.

How to use it: 
`scrip/./ToolAnalysisMyTools.sh configfileName` or 
`scrip./ToolAnalysisMyTools.sh "configfileName1,configfileName2,..."` or 
`scrip./ToolAnalysisMyTools.sh configfileName1 clean`

2025-08-21 17:38 UTC, jminock requested changes
Hi Marvin, overall code looks good. It doesn't change any original files which is good. Just 2 questions:
1) If I used this for a Toolchain but later want to compile everything, how would I do that? If it's just delete the "build_{configfileName} directory, could you please make that more clear?
2) Correct me if I'm wrong, but when you say "configfileName", do you mean the configfile sub directory for a full ToolChain and not an individual configfile for a single Tool? Could you please make this a little more clear?
I just want to make sure a new-ish user can understand everything on their own so neither of us need to follow up later on. Please add these clarifications to the documentation (thank you for including btw) and this will be good for merging!

2025-08-21 17:55 UTC, marvlad commented
1. It creates a temporary and independent directory (which it could be compressed with tar and set to the grid). The main code developing still happens on the `../ToolAnalysis `dir; hence the .build_{names} are in the git ignore file. I guess if one wants to develop and test there, the the config and Usertool need to be `mv` to the main dir. In summary, the script grabs all the necessary tools at the stage of the main `../ToolAnalysis dir`.

2. By configfileName I meant the subdirectory on the configfiles Example: In `configfiles/BeamFetcherV2/` the configfileName is `BeamFetcherV2` . But the script also allows multiple of them, example `'BeamFetcherV2,EventDisplay,...'`

2025-08-21 17:57 UTC, jminock approved these changes
Good to go!

2025-08-22 17:34 UTC, marc1uk commented
i believe this is superceded by #355 , the benefit of which is that it doesn't require duplicating files.

2025-09-04 09:37 UTC, brichards64 commented
superceded by https://github.com/ANNIEsoft/ToolAnalysis/pull/355 ,

2025-09-04 09:37 UTC, closed without merging